# Generated by Django 5.2.4 on 2025-08-08 10:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_rename_user_project_owner_project_description'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, help_text='Full name', max_length=100)),
                ('company', models.CharField(blank=True, help_text="Company's name", max_length=100)),
                ('team', models.CharField(blank=True, help_text='Team name', max_length=100)),
                ('position', models.CharField(blank=True, help_text='Job title or role', max_length=100)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
